# Generated by Django 4.0.3 on 2022-06-07 00:32
from django.db import migrations


def remove_bad_requests(apps, schema_editor):
    """ Function to remove requests requested to companies 
        which don't provide a requested service in that request.
    """
    ### Make sure we have old version of our model ###
    Request = apps.get_model("service_requests", "Request")
    removing_requests = [] # the list of ids of requests which are to be removed

    for request in Request.objects.all():
        requested_service = request.service
        requested_company = request.company
        company_services = requested_company.services.all()
        if requested_service not in company_services:
            removing_requests.append(request.id)

    for request_id in removing_requests:
        Request.objects.get(id = request_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code = remove_bad_requests, reverse_code = migrations.RunPython.noop)
    ]
