# Generated by Django 4.0.4 on 2022-05-09 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_service_description'),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.service'),
        ),
    ]
