# Generated by Django 4.0.3 on 2022-05-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='users.service'),
        ),
    ]
