# Generated by Django 4.0.3 on 2022-06-07 01:20
from django.db import migrations


def add_users_to_companies(apps, schema_editor):
    """ Function to add users to companies which don't have a user connected to them.
    """
    ### Make sure we have old version of our model ###
    Company = apps.get_model("users", "Company")
    User = apps.get_model("auth", "User")

    for company in Company.objects.all():
        if not company.user:
            # Create a User #
            company_user = User.objects.create(
                username = company.name + "_owner",
                password = company.name + "password1234"
            )
            # Assign the created user to a company #
            company.user = company_user
            company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_company_services'),
    ]

    operations = [
        migrations.RunPython(code = add_users_to_companies, reverse_code = migrations.RunPython.noop)
    ]
