# Generated by Django 4.0.3 on 2022-06-07 01:20
from django.db import migrations


def add_credentials(apps, schema_editor):
    """ Function to fill username and password fields for regular users and 
        companies which have these fields as empty.
    """
    ### Make sure we have old version of our model ###
    Company = apps.get_model("users", "Company")
    RegularUser = apps.get_model("users", "RegularUser")

    for company in Company.objects.all():
        if company.username is None:
            # Get the username from related User #
            username = company.user.username
            password = company.user.password
            # Assign taken credentials to a company #
            company.username, company.password = username, password
            company.save()
    
    for regular_user in RegularUser.objects.all():
        if regular_user.username is None:
            # Get the username from related User #
            username = regular_user.user.username
            password = regular_user.user.password
            # Assign taken credentials to a regular user #
            regular_user.username, regular_user.password = username, password
            regular_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_notification_user'),
    ]

    operations = [
        migrations.RunPython(code = add_credentials, reverse_code = migrations.RunPython.noop)
    ]
