# Generated by Django 4.0.3 on 2022-06-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220614_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='company',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
